--- #YAML:1.0
name:                CGI-ContactForm
version:             1.43
abstract:            Generate a web contact form
license:             ~
author:              
    - Gunnar Hjalmarsson <cpan@gunnar.cc>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Mail::Sender:                  0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
